#!/usr/bin/env bash

#NOTE: You must either copy this script to a directory stored in PATH (eg. /usr/local/bin), or add the directory where it is stored to PATH, otherwise use "bash multi_admixture ..."

HELP="
multi_admixture v.1.1

multi_admixture is a shell script for running ADMIXTURE across a range of k and/or over multiple iterations. ADMIXTURE must be installed prior to running this script.

USAGE: mutli_admixture [-f filename.ped] [-k int] [optional arguments]

REQUIRED ARGUMENTS:
-f|--file <filename>  : Input PLINK file with extension (must be in current working directory).
-k|--minK <int>       : Minimum k. If -K is not used, this will be the only k tested.

OPTIONAL ARGUMENTS:
-K|--maxK <int>       : Maximum k. Optional. This must be larger than -k
-i|--iterations <int> : Number of iterations. If not set, default is 1.
-j|--threads <int>    : Enables multi-threaded mode use n threads.
-cv <float/int>       : Enables cross-validation and sets the threshold. If no value is given with -cv, threshold defaults to 10.
-B|--bootstraps <int> : Enables bootstrapping and specifies number of replicates.
-S|--supervised       : Enables supervised mode. Must include a .pop file (see ADMIXTURE manual for details).
-P|--projection       : Enables projection analysis. Must include a reference .P file (see ADMIXTURE manual for details).
-s|--seed <int/str>   : Sets the random seed. If no value is given with -s, defaults to \$RANDOM.
-EM|--algorithm       : Use EM algorithm instead of block-relaxation.
-C|--majC <float/int> : Sets the major termination criterion.
-c|--minC <float/int> : Sets the minor termination criterion.
-a|--accel <str>      : Changes the acceleration method used (see ADMIXTURE manual for options).
-e|--epsilon <float>  : Enables penalized estimation and sets epsilon (must be less than 1).
-l|--lambda <float>   : Enables penalized estimation and sets lambda.
--haploid             : Use haploid data (default is diploid).
--help                : Displays help message.
"

if [[ $# -eq 0 ]]
then
	echo "$HELP"
	exit 1
fi

#Parse out variables from the command line
while [[ $# -gt 0 ]]
do
	key="$1"
	case $key in
		--help)
		echo "$HELP"
		exit 1
		;;
		-f|--file)
		FILE="$2"
		echo "Input file: $FILE"
		shift # past argument
		shift # past value
		;;
		-k|--minK)
		MINK="$2"
		echo "Minimum k: $MINK"
		shift # past argument
		shift # past value
		;;
		-K|--maxK)
		MAXK="$2"
		echo "Max k: $MAXK"
		shift
		shift
		;;
		-i|--iterations)
		ITERATIONS="$2"
		echo "Iterations: $ITERATIONS"
		shift # past argument
		shift # past value
		;;
		-j|--threads)
		THREADS="$2"
		echo "Requested parallel processing. Will use $THREADS threads."
		shift
		shift
		;;
		-B|--bootstraps)
		BOOTSTRAPS="$2"
		echo "Bootstrapping enabled. Replicates: $BOOTSTRAPS"
		shift
		shift
		;;
		-S|--supervised)
		SUPERVISED=YES
		shift
		;;
		-P|--projection)
		PROJECTION=YES
		shift
		;;
		-cv)
		CVon=YES
		if [[ -z "${2}" || "${2}" == -* ]]
		then
			CV=10
			echo "CV threshold: $CV"
			shift
		else
			CV="$2"
			echo "CV threshold: $CV"
			shift;shift
		fi
		;;
		-s|--seed)
		if [[ -z "$2" || "$2" == -* ]]
		then
			SEED=YES
			echo "Random seed: \$RANDOM"
			shift
		else
			SEED="$2"
			echo "Random seed: $SEED"
			shift;shift
		fi
		;;
		-EM|--algorithm)
		EM=YES
		echo "Using EM algorithm instead of block-relaxation."
		shift
		;;
		-C|--majC)
		MAJC="$2"
		echo "Major termination criterion: $MAJC"
		shift
		shift
		;;
		-c|--minC)
		MINC="$2"
		echo "Minor termination criterion: $MINC"
		shift
		shift
		;;
		-a|--accel)
		ACCEL="$2"
		echo "Accerlation method changed: $ACCEL"
		shift
		shift
		;;
		-e|--epsilon)
		EPSILON="$2"
		echo "Penalized estimation enabled. Epsilon: $EPSILON"
		shift
		shift
		;;
		-l|--lambda)
		LAMBDA="$2"
		echo "Penalized estimation enabled. Lambda: $LAMBDA"
		shift
		shift
		;;
		-h|--haploid)
		HAPLOID=YES
		echo "Data is haploid."
		shift
		;;
	esac
done

ERROR=0

#These commands check that all the necessary values are present, and sets defaults for optional arguments
if [[ -z "${FILE}" ]]
then
  echo "Please specify input file (-f | --file)."
  ERROR=1
fi

if [[ -z "${MINK}" ]]
then
  echo "Please specify at least one k value (-k | --minK)."
  ERROR=1
fi

if [[ -z "${MAXK}" ]]
then
	KRANGE=NO
else
	KRANGE=YES
fi

if [[ "${KRANGE}" == YES && "${MAXK}" -le "${MINK}" ]]
then
  echo "Error: Max K less than or equal to min K. Use a greater value (-K | --maxK)."
  ERROR=1
fi

if [[ -z "${ITERATIONS}" ]]
then
	ITERATIONS=1
fi

if [[ -z "${THREADS}" ]]
then
	PARALLEL=NO
else
	PARALLEL=YES
fi

if [[ -z "${BOOTSTRAPS}" ]]
then
	BOOT=NO
else
	BOOT=YES
fi

if [[ -z "${SUPERVISED}" ]]
then
	SUPERVISED=NO
fi

if [[ -z "${PROJECTION}" ]]
then
	PROJECTION=NO
fi

if [[ "${SUPERVISED}" == YES && "${PROJECTION}" == YES ]]
then
	echo "Please specify only one of -S or -P."
	ERROR=1
elif [[ "${SUPERVISED}" == YES && "${PROJECTION}" == NO ]]
then
	echo "Will perform supervised analysis."
elif [[ "${SUPERVISED}" == NO && "${PROJECTION}" == YES ]]
then
	echo "Will perform projection analysis."
fi

if [[ -n "${EPSILON}" && ${EPSILON%.*} -ge 1 ]]
then
  echo "Epsilon must be less than 1."
  ERROR=1
fi
	
if [[ "${ERROR}" -ne "0" ]]
then
  echo -e ${USAGE}
  exit 1
fi

echo "Successfully parsed variables."

#Builds and runs the script
if [[ $ITERATIONS -eq 1 && "${KRANGE}" == NO ]] #Single K, one iteration
then
	COMMAND="admixture $FILE $MINK"
	if [[ $CVon == YES ]]
	then
		COMMAND="$COMMAND --cv=$CV"
	fi
	if [[ $SEED == YES ]]
	then
		COMMAND="$COMMAND -s $RANDOM"
	elif [[ -n $SEED && $SEED != YES ]]
	then
		COMMAND="$COMMAND -s $SEED"
	fi
	if [[ "${PARALLEL}" == YES ]]
	then
		COMMAND="$COMMAND -j${THREADS}"
	fi
	if [[ "$BOOT" == YES ]]
	then
		COMMAND="$COMMAND -B${BOOTSTRAPS}"
	fi
	if [[ "$PROJECTION" == YES ]]
	then
		COMMAND="$COMMAND -P"
	fi
	if [[ "$SUPERVISED" == YES ]]
	then
		COMMAND="$COMMAND --supervised"
	fi
	if [[ -n $EPSILON ]]
	then
		COMMAND="$COMMAND -e $EPSILON"
	fi
	if [[ -n $LAMBDA ]]
	then
		COMMAND="$COMMAND -l $LAMBDA"
	fi
	if [[ $EM == YES ]]
	then
		COMMAND="$COMMAND -m EM"
	fi
	if [[ -n $MAJC ]]
	then
		COMMAND="$COMMAND -C $MAJC"
	fi
	if [[ -n $MINC ]]
	then
		COMMAND="$COMMAND -c $MINC"
	fi
	if [[ -n $ACCEL ]]
	then
		COMMAND="$COMMAND -a $ACCEL"
	fi
	if [[ $HAPLOID == YES ]]
	then
		COMMAND="$COMMAND --haploid"
	fi
	COMMAND="$COMMAND | tee log.out"
	eval OMMAND
		exit 1
	echo
	echo
elif [[ $ITERATIONS -gt 1 && "${KRANGE}" == NO ]] #Single K, multiple iterations
then
	N=1
	while [[ $N -le $ITERATIONS ]];do
		mkdir run_$N
		cd run_$N
		COMMAND="admixture ../$FILE $MINK"
		if [[ $CVon == YES ]]
		then
			COMMAND="$COMMAND --cv=$CV"
		fi
		if [[ $SEED == YES ]]
		then
			COMMAND="$COMMAND -s $RANDOM"
		elif [[ -n $SEED && $SEED != YES ]]
		then
			COMMAND="$COMMAND -s $SEED"
		fi
		if [[ "${PARALLEL}" == YES ]]
		then
			COMMAND="$COMMAND -j${THREADS}"
		fi
		if [[ "$BOOT" == YES ]]
		then
			COMMAND="$COMMAND -B${BOOTSTRAPS}"
		fi
		if [[ "$PROJECTION" == YES ]]
		then
			COMMAND="$COMMAND -P"
		fi
		if [[ "$SUPERVISED" == YES ]]
		then
			COMMAND="$COMMAND --supervised"
		fi
		if [[ -n $EPSILON ]]
		then
			COMMAND="$COMMAND -e $EPSILON"
		fi
		if [[ -n $LAMBDA ]]
		then
			COMMAND="$COMMAND -l $LAMBDA"
		fi
		if [[ $EM == YES ]]
		then
			COMMAND="$COMMAND -m EM"
		fi
		if [[ -n $MAJC ]]
		then
			COMMAND="$COMMAND -C $MAJC"
		fi
		if [[ -n $MINC ]]
		then
			COMMAND="$COMMAND -c $MINC"
		fi
		if [[ -n $ACCEL ]]
		then
			COMMAND="$COMMAND -a $ACCEL"
		fi
		if [[ $HAPLOID == YES ]]
		then
			COMMAND="$COMMAND --haploid"
		fi
		COMMAND="$COMMAND | tee log.out"
		eval OMMAND
		cd ../
		N=$((N+1))
	done
	if [[ $CVon == YES ]]
	then
		grep -h "CV" ./run*/log.out >> CV_scores.txt
	fi
elif [[ $ITERATIONS -eq 1 && "${KRANGE}" == YES ]] #Range of K, one iteration
then
	for K in $(eval echo "{$MINK..$MAXK}");do
		mkdir P_outs Q_outs logs
		COMMAND="admixture $FILE $K"
		if [[ $CVon == YES ]]
		then
			COMMAND="$COMMAND --cv=$CV"
		fi
		if [[ $SEED == YES ]]
		then
			COMMAND="$COMMAND -s $RANDOM"
		elif [[ -n $SEED && $SEED != YES ]]
		then
			COMMAND="$COMMAND -s $SEED"
		fi
		if [[ "${PARALLEL}" == YES ]]
		then
			COMMAND="$COMMAND -j${THREADS}"
		fi
		if [[ "$BOOT" == YES ]]
		then
			COMMAND="$COMMAND -B${BOOTSTRAPS}"
		fi
		if [[ "$PROJECTION" == YES ]]
		then
			COMMAND="$COMMAND -P"
		fi
		if [[ "$SUPERVISED" == YES ]]
		then
			COMMAND="$COMMAND --supervised"
		fi
		if [[ -n $EPSILON ]]
		then
			COMMAND="$COMMAND -e $EPSILON"
		fi
		if [[ -n $LAMBDA ]]
		then
			COMMAND="$COMMAND -l $LAMBDA"
		fi
		if [[ $EM == YES ]]
		then
			COMMAND="$COMMAND -m EM"
		fi
		if [[ -n $MAJC ]]
		then
			COMMAND="$COMMAND -C $MAJC"
		fi
		if [[ -n $MINC ]]
		then
			COMMAND="$COMMAND -c $MINC"
		fi
		if [[ -n $ACCEL ]]
		then
			COMMAND="$COMMAND -a $ACCEL"
		fi
		if [[ $HAPLOID == YES ]]
		then
			COMMAND="$COMMAND --haploid"
		fi
		COMMAND="$COMMAND | tee log_$K.out"
		eval OMMAND
		if [[ $CVon == YES ]]
		then
			grep -h "CV" log_$K.out >> CV_scores.txt
		fi
		mv *.Q ./Q_outs;mv *.P ./P_outs/;mv log_$K.out ./logs/
	done
else #Range of k, multiple iterations
	for N in $(eval echo "{1..$ITERATIONS}");do
	mkdir run_$N
	cd run_$N
	for K in $(eval echo "{$MINK..$MAXK}");do
		mkdir P_outs Q_outs logs
		COMMAND="admixture ../$FILE $K"
		if [[ $CVon == YES ]]
		then
			COMMAND="$COMMAND --cv=$CV"
		fi
		if [[ $SEED == YES ]]
		then
			COMMAND="$COMMAND -s $RANDOM"
		elif [[ -n $SEED && $SEED != YES ]]
		then
			COMMAND="$COMMAND -s $SEED"
		fi
		if [[ "${PARALLEL}" == YES ]]
		then
			COMMAND="$COMMAND -j${THREADS}"
		fi
		if [[ "$BOOT" == YES ]]
		then
			COMMAND="$COMMAND -B${BOOTSTRAPS}"
		fi
		if [[ "$PROJECTION" == YES ]]
		then
			COMMAND="$COMMAND -P"
		fi
		if [[ "$SUPERVISED" == YES ]]
		then
			COMMAND="$COMMAND --supervised"
		fi
		if [[ -n $EPSILON ]]
		then
			COMMAND="$COMMAND -e $EPSILON"
		fi
		if [[ -n $LAMBDA ]]
		then
			COMMAND="$COMMAND -l $LAMBDA"
		fi
		if [[ $EM == YES ]]
		then
			COMMAND="$COMMAND -m EM"
		fi
		if [[ -n $MAJC ]]
		then
			COMMAND="$COMMAND -C $MAJC"
		fi
		if [[ -n $MINC ]]
		then
			COMMAND="$COMMAND -c $MINC"
		fi
		if [[ -n $ACCEL ]]
		then
			COMMAND="$COMMAND -a $ACCEL"
		fi
		if [[ $HAPLOID == YES ]]
		then
			COMMAND="$COMMAND --haploid"
		fi
		COMMAND="$COMMAND | tee log_$K.out"
		eval OMMAND
		if [[ $CVon == YES ]]
		then
			grep -h "CV" log_$K.out >> CV_scores$N.txt
		fi
		mv *.Q ./Q_outs;mv *.P ./P_outs/;mv log_$K.out ./logs/
	done
	cd ../
	done
	if [[ $CVon == YES ]]
	then
		cat ./run*/CV_scores* >> allCV.txt
	fi
fi
